import Head from 'next/head'
import ProjectViewList from './components/ProjectViewList.js'
import Header from './components/Header.js'
import Footer from './components/Footer.js'

export default function ProjectPage() {
  const title = "1000 Cheng";
  return (
    <div>

      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/icons/logo_32.png" />
      </Head>

      <Header location="/" title={title} />
      <div className="container" >
        <ProjectViewList type="default"></ProjectViewList>
      </div>
      <Footer />

    </div>
  )
}
