import Head from 'next/head'
import MediaList from './components/MediaList.js'
import Header from './components/Header.js'
import Footer from './components/Footer.js'

export default function LabPage() {
  const title = "Lab | 1000 Cheng";
  return (
    <div>

      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/icons/logo_32.png" />
      </Head>

      <Header location="/lab" title={title} />

      <div className="container" >
        <div className="project-container">
          <MediaList col={4} mCol={2}
            links={[
              "lab.lab01",
              "lab.lab02",
              //"lab.lab03",
              "lab.lab04",
              "lab.lab05",
              "lab.lab06",
              "lab.lab07",
              "lab.lab08",
              "lab.lab09",
              "lab.lab10",
              "lab.lab11",
              "lab.lab12",
            ]} />
        </div>
      </div>
      
      <Footer />

    </div>
  )
}
