import React from "react";
import Head from 'next/head'
import Header from './/Header.js'
import Footer from './/Footer.js'
import ProjectViewList from ".//ProjectViewList.js";
import { projectData } from "../../data.js";

/**
 * 
 * Project 的統一容器。
 * 
 * @id 指定這個 Project 的 id
 */
export default function Project(props) {

  const { id, } = props;

  const project = projectData.projects.find((proj) => proj.id == id) || { title: "N/A" };

  return (
    <div>

      <Head>
        <title>{project.title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/icons/logo_32.png" />
      </Head>

      <Header />

      <div className="container" >
        <div className="project-container">

          {props.children}

          <div className="related-project-container">
            <div className="project-text-container project-view-title">
              <h2>Related Projects</h2>
            </div>
            <ProjectViewList
              projectType="default"
              randomPick={3} />
          </div>

        </div>
      </div>

      <Footer />

    </div>);
}